### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by 0x6e69636f**
- Add a favicon to the page 
- Add some infos about PostgreSQL prerequisites in the Readme
- Add javax.xml.bind dependency to the pom.xml 
- Suggestion : don't remove Constant Pool stuff from output

### CODE REVIEW

**Review by yawkat — CHANGES_REQUESTED** [review]
The constant pool unfortunately appears before the actual class bytecode and so clutters the output. This is the reason why it is excluded at this time. Maybe there could be a separate tab with javap constant pool output included, or there could be an expander in the UI. Both of these are a little more work though

**Comment by 0x6e69636f** [comment]
@yawkat yes could be cool, but since the editor only allows to paste a single "autonomous" class (i.e : it can't decompile a complex class with dependencies), I think it's interesting to see the constants and the whole output

But if you want to remove them, I think you can also just remove the `-v` param from `javap` call

**Comment by yawkat** [comment]
Cherry-picked into master as 677c475769ce0265cf418d05ea5b90e968b62f50 and 1d6309f89870894f3f8fac9640163ff395f1aa80 . Thank you for the contribution!

**Comment by yawkat** [comment]
to come back to the constant pool part: ive revamped the ui, and it now has the constant pool included but collapsed by default.

**Comment by 0x6e69636f** [comment]
@yawkat really cool ! 👍

**Pull request closed without merging**
